1password:
  install:
    if_fail: sudo dnf list --installed 1password
    install_from_remote_file: https://downloads.1password.com/linux/rpm/stable/x86_64/1password-latest.rpm

aws-cli:
  install:
    if_fail: sudo dnf list --installed awscli2
    install_from_repo: awscli2
  files:
    ./data-secret/aws/config: ${HOME}/.aws/config

bash:
  files:
    ./data-secret/bash/default_environment_variables: ${HOME}/.default_environment_variables
    ./data/bash/bash_profile: ${HOME}/.bash_profile
    ./data/bash/custom_bash_prompt.sh: /etc/profile.d/custom_bash_prompt.sh

cloudflare-warp:
  install:
    if_fail: sudo dnf list --installed cloudflare-warp
    repo: https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo
    install_from_repo: cloudflare-warp

crypto-policies:
  files:
    ./data/crypto-policies/legacy-openssl.txt: /usr/share/crypto-policies/LEGACY/openssl.txt

google-chrome:
  install:
    if_fail: sudo dnf list --installed google-chrome-stable
    install_from_remote_file: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

kubectl:
  install:
    if_fail: which kubectl
    install_script: |
      #!/bin/bash
      version=$(curl -L -s https://dl.k8s.io/release/stable.txt)
      sudo wget -q -P /usr/local/bin "https://dl.k8s.io/release/$version/bin/linux/amd64/kubectl"
      sudo chmod +x /usr/local/bin/kubectl

nmap:
  install:
    if_fail: sudo dnf list --installed nmap
    install_from_repo: nmap

openssh-server:
  install:
    if_fail: sudo dnf list --installed openssh-server
    install_from_repo: openssh-server
  files:
    ./data/openssh-server/sshd_config: /etc/ssh/sshd_config.d/sshd_config.conf

slack:
  install:
    if_fail: sudo dnf list --installed slack
    install_from_remote_file: https://downloads.slack-edge.com/desktop-releases/linux/x64/4.39.88/slack-4.39.88-0.1.el8.x86_64.rpm

solaar:
  install:
    if_fail: sudo dnf list --installed solaar
    install_from_repo: solaar

terminator:
  install:
    if_fail: sudo dnf list --installed terminator
    install_from_repo: terminator
  files:
    ./data/terminator/config: ${HOME}/.config/terminator/config

tfenv:
  install:
    if_fail: ls ${HOME}/.tfenv
    install_script: |
      #!/bin/bash
      git clone --depth=1 https://github.com/tfutils/tfenv.git ${HOME}/.tfenv

tgenv:
  install:
    if_fail: ls ${HOME}/.tgenv
    install_script: |
      #!/bin/bash
      git clone --depth=1 https://github.com/cunymatthieu/tgenv.git ${HOME}/.tgenv

vscode:
  install:
    if_fail: sudo dnf list --installed code
    install_from_remote_file: https://vscode.download.prss.microsoft.com/dbazure/download/stable/5437499feb04f7a586f677b155b039bc2b3669eb/code-1.90.2-1718751675.el8.x86_64.rpm

yq:
  install:
    if_fail: sudo dnf list --installed yq
    install_from_repo: yq
