# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# Get the default aliases
if [ -f ~/.default_aliases ]; then
    . ~/.default_aliases
fi

# Get the default environment variables
if [ -f ~/.default_environment_variables ]; then
    . ~/.default_environment_variables
fi

# Arbitrary environment variables
export PATH="$PATH:$HOME/.tfenv/bin"
export PATH="$PATH:$HOME/.tgenv/bin"
